name: 'Generate Github app access token'
description: 'Generates an access token for a github app'
author: 'Allopneus'
inputs:
  app_id:
    description: 'Your github application id'
    required: true
  app_installation_id:
    description: 'Your github app installation id'
    required: true
  app_private_key:
    description: 'One of your github app private keys'
    required: true
  app_client_id:
    description: 'The app client id'
    required: true
  app_client_secret:
    description: 'The app client secret'
    required: true
outputs:
  installation_token:
    description: 'A github app access token'
runs:
  using: 'node12'
  main: 'dist/index.js'
